/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.views;
import javax.swing.ImageIcon;



import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import br.dao.ClienteDAO;
import br.dao.EletronicoDAO;
import br.beans.Cliente;
import br.beans.Eletronico;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.border.LineBorder;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.JSpinner;

/**
 *
 * @author adrya
 */
public class RegistroEletronico extends javax.swing.JFrame {

   // private final CadastroClienteController controller;
	/**
     * Creates new form NewJFrame
     */
    public RegistroEletronico() {
        initComponents();
       // controller = new CadastroClienteController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Tahoma", Font.BOLD, 11));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Tahoma", Font.BOLD, 11));
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setFont(new Font("Tahoma", Font.BOLD, 11));
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setFont(new Font("Tahoma", Font.BOLD, 11));
        txtNumSerial = new javax.swing.JTextField();
        txtNumSerial.setBackground(new Color(235, 237, 241));
        txtMarca = new javax.swing.JTextField();
        txtMarca.setBackground(new Color(235, 237, 241));
        txtTipo = new javax.swing.JTextField();
        txtTipo.setBackground(new Color(235, 237, 241));
        txtModelo = new javax.swing.JTextField();
        txtModelo.setBackground(new Color(235, 237, 241));
        txtModelo.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		jButtonCadastrar.setEnabled(true);
        	}
        });
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setBackground(new Color(235, 237, 241));
        jButtonCadastrar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        JButton btnLimpar = new JButton("Limpar");
        btnLimpar.addFocusListener(new FocusAdapter() {
 
        });
        jButtonAlterar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		String numSerial, tipo, marca, modelo, cpf;
        		
        		numSerial = txtNumSerial.getText();
                tipo = txtTipo.getText();
                marca = txtMarca.getText();
                modelo = txtModelo.getText();
                cpf = txtCpf.getText();
                
                Cliente cli =new Cliente();
                ClienteDAO cliDao = new ClienteDAO();
       
                cli = cliDao.buscarClientes(cpf);
                
                Eletronico eletr = new Eletronico(numSerial, tipo, marca, modelo,cli);
                EletronicoDAO eletrDAO = new EletronicoDAO();
                
                if(eletrDAO.atualizarEletronico(eletr)){
                    JOptionPane.showMessageDialog(null, "Alteração EFETUADA com Sucesso!","Resultado",JOptionPane.INFORMATION_MESSAGE);
                    
                    preencherTbl();
               }else{
                    JOptionPane.showMessageDialog(null, "NAO FOI POSSÍVEL ALTERAR!","Resultado",JOptionPane.ERROR_MESSAGE);
               }
        	}
        });
        jButtonExcluir = new javax.swing.JButton();
        jButtonExcluir.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        	String numSerial, tipo, marca, modelo, cpf;
                
            numSerial = txtNumSerial.getText();
            tipo = txtTipo.getText();
            marca = txtMarca.getText();
            modelo = txtModelo.getText();
            cpf = txtCpf.getText();
            
            Cliente cli = new Cliente();
            ClienteDAO cliDAO = new ClienteDAO();
            
            cli = cliDAO.buscarClientes(cpf);
  
            Eletronico eletr = new Eletronico(numSerial, tipo, marca, modelo, cli);
                
            EletronicoDAO eletrDAO = new EletronicoDAO();
                
            if(eletrDAO.excluirEletronico(eletr)){
                 JOptionPane.showMessageDialog(null, "EXCLUSÃO EFETUADA com Sucesso!","Resultado",JOptionPane.INFORMATION_MESSAGE);
                 
                 preencherTbl();
            }else{
                 JOptionPane.showMessageDialog(null, "NAO FOI POSSÍVEL EXCLUIR!","Resultado",JOptionPane.ERROR_MESSAGE);
            }
            
        
           jButtonExcluir.setEnabled(false);
      
        	}
        });
        txtBuscarNumSerial = new javax.swing.JTextField();
        txtBuscarNumSerial.setToolTipText("Informe um Id");
        txtBuscarNumSerial.setForeground(new Color(0, 0, 0));
        jScrollPane2 = new javax.swing.JScrollPane();
        tableEletronicos = new javax.swing.JTable();
        tableEletronicos.setFont(new Font("Tahoma", Font.PLAIN, 12));
        tableEletronicos.setForeground(new Color(0, 0, 0));
        tableEletronicos.setBackground(new Color(235, 237, 241));
        tableEletronicos.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent e) {
        		
        		int selectRow = tableEletronicos.getSelectedRow();
        		
        		txtNumSerial.setText(tableEletronicos.getValueAt(selectRow, 0).toString());
        		txtTipo.setText(tableEletronicos.getValueAt(selectRow, 1).toString());
        		txtMarca.setText(tableEletronicos.getValueAt(selectRow, 2).toString());
        		txtModelo.setText(tableEletronicos.getValueAt(selectRow, 3).toString());
        		txtCpf.setText(tableEletronicos.getValueAt(selectRow, 5).toString());
        		
        	}
        });
        tableEletronicos.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusGained(FocusEvent e) {
        		jButtonExcluir.setEnabled(true);
        		jButtonAlterar.setEnabled(true);
        		btnLimpar.setEnabled(true);
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(226, 255, 128));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new Color(55, 52, 95));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eletrônico");

        jLabel2.setForeground(new Color(55, 52, 95));
        jLabel2.setText("Número Serial");

        jLabel3.setForeground(new Color(55, 52, 95));
        jLabel3.setText("Marca");

        jLabel4.setForeground(new Color(55, 52, 95));
        jLabel4.setText("Tipo");

        jLabel5.setForeground(new Color(55, 52, 95));
        jLabel5.setText("Modelo");

        txtNumSerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        txtTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButtonCadastrar.setText("Salvar");
        jButtonCadastrar.setEnabled(false);
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        
        JButton btnBuscar = new JButton("");
        btnBuscar.setBackground(new Color(240, 240, 240));
        btnBuscar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String numSerial = txtBuscarNumSerial.getText();
        		
        		EletronicoDAO eletrDao = new EletronicoDAO();
        		Eletronico eletr = new Eletronico();
        		
        		eletr = eletrDao.buscarEletronicos(numSerial);
        		
        		txtNumSerial.setText(eletr.getNumSerial());
        		txtTipo.setText(eletr.getTipo());
        		txtMarca.setText(eletr.getMarca());
        		txtModelo.setText(eletr.getModelo());
        		txtCpf.setText(eletr.getCliente().getCpf());
        		
        		jButtonExcluir.setEnabled(true);
                jButtonAlterar.setEnabled(true);

        	}
        });
        btnBuscar.setIcon(new ImageIcon(RegistroEletronico.class.getResource("/imgsCadastro/pesquisar.png")));
       
        btnLimpar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		txtNumSerial.setText(null);
        		txtTipo.setText(null);
        		txtMarca.setText(null);
        		txtModelo.setText(null);
        		txtCpf.setText(null);
        		
        		btnLimpar.setEnabled(false);
        	}
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(27)
        			.addComponent(jButtonCadastrar)
        			.addGap(18)
        			.addComponent(jButtonAlterar)
        			.addGap(18)
        			.addComponent(jButtonExcluir)
        			.addGap(18)
        			.addComponent(btnLimpar)
        			.addPreferredGap(ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
        			.addComponent(btnBuscar)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(txtBuscarNumSerial, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
        			.addGap(19))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButtonCadastrar)
        				.addComponent(jButtonAlterar)
        				.addComponent(jButtonExcluir)
        				.addComponent(txtBuscarNumSerial, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnBuscar, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnLimpar))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        tableEletronicos.setModel(new DefaultTableModel(
        	new Object[][] {
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        		{null, null, null, null, null, null},
        	},
        	new String[] {
        		"N\u00FAm Serial", "Tipo", "Marca", "Modelo", "Cliente", "Cpf"
        	}
        ));
        tableEletronicos.getColumnModel().getColumn(0).setPreferredWidth(50);
        tableEletronicos.getColumnModel().getColumn(1).setPreferredWidth(90);
        tableEletronicos.getColumnModel().getColumn(3).setPreferredWidth(90);
        jScrollPane2.setViewportView(tableEletronicos);
        
        lblNewLabel = new JLabel("Cpf do Cliente");
        lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 11));
        lblNewLabel.setForeground(new Color(55, 52, 95));
        
        txtCpf = new JTextField();
        txtCpf.setBackground(new Color(235, 237, 241));
        txtCpf.setColumns(10);
        
        JLabel lblNewLabel_1 = new JLabel("");
        
        JLabel lblNewLabel_2 = new JLabel("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jLabel2)
        						.addComponent(txtMarca)
        						.addComponent(txtNumSerial, GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        						.addComponent(jLabel3))
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel5)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        							.addComponent(txtModelo, Alignment.LEADING)
        							.addComponent(txtTipo, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
        							.addComponent(lblNewLabel_1, Alignment.LEADING))
        						.addComponent(jLabel4))
        					.addGap(173))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addContainerGap())))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblNewLabel)
        			.addContainerGap(504, Short.MAX_VALUE))
        		.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(txtCpf, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
        			.addComponent(lblNewLabel_2)
        			.addGap(329))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(jLabel4))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtNumSerial, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtTipo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(3)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(jLabel5))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtMarca, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtModelo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabel)
        				.addComponent(lblNewLabel_1))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtCpf, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblNewLabel_2))
        			.addGap(18)
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //executa quando clica no botão
    	String numSerial, tipo, marca, modelo, cpf;
    	
    	
    	numSerial = txtNumSerial.getText();
    	tipo = txtTipo.getText();
    	marca = txtMarca.getText();
    	modelo = txtModelo.getText();
    	cpf = txtCpf.getText();
    	
    	Cliente cli = new Cliente();
    	ClienteDAO cliDao = new ClienteDAO();
    	cli = cliDao.buscarClientes(cpf);
    	
		Eletronico eletr = new Eletronico(numSerial, tipo, marca, modelo, cli);
		EletronicoDAO eletrDAO = new EletronicoDAO();
    	
    	 if(eletrDAO.inserirEletronico(eletr)){	
    		 
             JOptionPane.showMessageDialog(null, "Cadastro Realizado com Sucesso!","Resultado",JOptionPane.INFORMATION_MESSAGE);
             
             txtNumSerial.setText(null);
         	 txtTipo.setText(null);
         	 txtMarca.setText(null);
         	 txtModelo.setText(null);
         	 txtCpf.setText(null);
         	 
         	 preencherTbl();
         	
         }else{
             JOptionPane.showMessageDialog(null, "NAO FOI POSSÍVEL CADASTRAR!","Resultado",JOptionPane.ERROR_MESSAGE);
         }
    	 
    	 jButtonCadastrar.setEnabled(true);
    	
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */     
    public void preencherTbl() {
    	EletronicoDAO eletrDAO = new EletronicoDAO();
    	List<Eletronico> lista = eletrDAO.listarEletronicos();
    	
    	DefaultTableModel modelo = (DefaultTableModel) tableEletronicos.getModel();
    	modelo.setRowCount(0);
    	
    	for (Eletronico eletronico : lista) {
    		modelo.addRow(new Object[]{eletronico.getNumSerial(),eletronico.getTipo(), eletronico.getMarca(), eletronico.getModelo(),
    				eletronico.getCliente().getNome(), eletronico.getCliente().getCpf()});
    	}
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEletronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEletronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEletronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEletronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEletronico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableEletronicos;
    private javax.swing.JTextField txtNumSerial;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtBuscarNumSerial;
    private JLabel lblNewLabel;
    private JTextField txtCpf;
    // End of variables declaration//GEN-END:variables
	public void exibeMensagem(String mensagem) {
		JOptionPane.showMessageDialog(null, mensagem);
	}

	public javax.swing.JTextField getjTextFieldNome() {
		return txtNumSerial;
	}

	public void setjTextFieldNome(javax.swing.JTextField jTextFieldNome) {
		this.txtNumSerial = jTextFieldNome;
	}

	public javax.swing.JTextField getjTextEndereco() {
		return txtMarca;
	}

	public void setjTextEndereco(javax.swing.JTextField jTextEndereco) {
		this.txtMarca = jTextEndereco;
	}

	public javax.swing.JTextField getjTextFieldCpf() {
		return txtTipo;
	}

	public void setjTextFieldCpf(javax.swing.JTextField jTextFieldCpf) {
		this.txtTipo = jTextFieldCpf;
	}

	public javax.swing.JTextField getjTextFieldTelefone() {
		return txtModelo;
	}

	public void setjTextFieldTelefone(javax.swing.JTextField jTextFieldTelefone) {
		this.txtModelo = jTextFieldTelefone;
	}
}
