/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.views;
import javax.swing.ImageIcon;



import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.border.LineBorder;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import javax.swing.JPanel;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;

/**
 *
 * @author adrya
 */
public class RegistroOrdemServico extends javax.swing.JFrame {

   // private final CadastroClienteController controller;
	/**
     * Creates new form NewJFrame
     */
    public RegistroOrdemServico() {
		setForeground(new Color(55, 52, 95));
		setTitle("Ordem de Servico");
        initComponents();
       // controller = new CadastroClienteController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Tahoma", Font.BOLD, 11));
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setFont(new Font("Tahoma", Font.BOLD, 11));
        txtIdSO = new javax.swing.JTextField();
        txtIdSO.setBackground(new Color(235, 237, 241));
        txtEletronico = new javax.swing.JTextField();
        txtEletronico.setBackground(new Color(235, 237, 241));
        txtDtConclusao = new javax.swing.JTextField();
        txtDtConclusao.setBackground(new Color(235, 237, 241));
        txtDtConclusao.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		jButtonCadastrar.setEnabled(true);
        	}
        });
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setBackground(new Color(235, 237, 241));
        jButtonCadastrar = new javax.swing.JButton();
        JButton btnLimpar = new JButton("Limpar");
        btnLimpar.addFocusListener(new FocusAdapter() {
 
        });
        jButtonExcluir = new javax.swing.JButton();
        jButtonExcluir.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        	String nome, cpf, endereco, telefone, email;
            
        	long id = Long.parseLong(txtId.getText());
            nome = txtIdSO.getText();
            cpf = txtCpf.getText();
            endereco = txtEletronico.getText();
            telefone = txtDtConclusao.getText();
            email = txtServico.getText();
  
            Tecnico tec = new Tecnico(id, nome,cpf, endereco, telefone,email);
                
            TecnicoDAO tecDAO = new TecnicoDAO();
                
            if(tecDAO.excluirTecnico(tec)){
                 JOptionPane.showMessageDialog(null, "EXCLUSÃO EFETUADA com Sucesso!","Resultado",JOptionPane.INFORMATION_MESSAGE);
                 
                 preencherTbl();
            }else{
                 JOptionPane.showMessageDialog(null, "NAO FOI POSSÍVEL EXCLUIR!","Resultado",JOptionPane.ERROR_MESSAGE);
            }
            
        
           jButtonExcluir.setEnabled(false);
      
        	}
        });
        txtBuscarIdSo = new javax.swing.JTextField();
        txtBuscarIdSo.setToolTipText("Informe um Id");
        txtBuscarIdSo.setForeground(new Color(0, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(226, 255, 128));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new Color(55, 52, 95));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ordem de Serviço");

        jLabel2.setForeground(new Color(55, 52, 95));
        jLabel2.setText("Id OS");

        jLabel5.setForeground(new Color(55, 52, 95));
        jLabel5.setText("Conclusão");

        txtIdSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        txtEletronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButtonCadastrar.setText("Salvar");
        jButtonCadastrar.setEnabled(false);
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        
        JButton btnBuscar = new JButton("");
        btnBuscar.setBackground(new Color(240, 240, 240));
        btnBuscar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		long id = Long.parseLong(txtBuscarIdSo.getText());
        		
        		TecnicoDAO tecDao = new TecnicoDAO();
        		Tecnico tec = new Tecnico();
        		
        		tec = tecDao.buscarTecnicos(id);
        		
        		txtIdSO.setText(tec.getNome());
        		txtCpf.setText(tec.getCpf());
        		txtEletronico.setText(tec.getEndereco());
        		txtDtConclusao.setText(tec.getTelefone());
        		txtServico.setText(tec.getEmail());
        		
        		jButtonExcluir.setEnabled(true);
                jButtonAlterar.setEnabled(true);

        	}
        });
        btnBuscar.setIcon(new ImageIcon(RegistroOrdemServico.class.getResource("/imgsCadastro/pesquisar.png")));
       
        btnLimpar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		txtIdSO.setText(null);
        		txtCpf.setText(null);
        		txtEletronico.setText(null);
        		txtDtConclusao.setText(null);
        		txtServico.setText(null);
        		
        		btnLimpar.setEnabled(false);
        	}
        });
        
        btnNewButton = new JButton("Alterar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(27)
        			.addComponent(jButtonCadastrar)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(btnNewButton)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jButtonExcluir)
        			.addGap(92)
        			.addComponent(btnLimpar)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(btnBuscar)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(txtBuscarIdSo, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(txtBuscarIdSo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnBuscar, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jButtonCadastrar)
        					.addComponent(jButtonExcluir)
        					.addComponent(btnNewButton)
        					.addComponent(btnLimpar)))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);
        
        lblNewLabel_1 = new JLabel("Eletrônico");
        lblNewLabel_1.setFont(new Font("Tahoma", Font.BOLD, 11));
        lblNewLabel_1.setForeground(new Color(55, 52, 95));
        
        Servico = new JLabel("Serviço");
        Servico.setFont(new Font("Tahoma", Font.BOLD, 11));
        Servico.setForeground(new Color(55, 52, 95));
        
        JComboBox comboBoxTecnico = new JComboBox();
        
        JLabel lblNewLabel_3 = new JLabel("Defeito");
        lblNewLabel_3.setFont(new Font("Tahoma", Font.BOLD, 11));
        lblNewLabel_3.setForeground(new Color(55, 52, 95));
        
        JTextArea textDefeito = new JTextArea();
        
        JLabel lblNewLabel_4 = new JLabel("Avarias");
        lblNewLabel_4.setFont(new Font("Tahoma", Font.BOLD, 11));
        lblNewLabel_4.setForeground(new Color(55, 52, 95));
        
        JTextArea textAvarias = new JTextArea();
        
        JLabel lblNewLabel_5 = new JLabel("Valor Total");
        lblNewLabel_5.setFont(new Font("Tahoma", Font.BOLD, 11));
        lblNewLabel_5.setForeground(new Color(55, 52, 95));
        
        textValorTotal = new JTextField();
        textValorTotal.setColumns(10);
        
        lblNewLabel_2 = new JLabel("Técnico");
        lblNewLabel_2.setFont(new Font("Tahoma", Font.BOLD, 11));
        lblNewLabel_2.setForeground(new Color(55, 52, 95));
        
        comboBoxServicos = new JComboBox();
        
        lblNewLabel = new JLabel(" Cpf do Cliente");
        lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 11));
        lblNewLabel.setForeground(new Color(55, 52, 95));
        
        textCpfCliente = new JTextField();
        textCpfCliente.setColumns(10);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addComponent(lblNewLabel_1)
        						.addGap(228))
        					.addGroup(jPanel1Layout.createSequentialGroup()
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        							.addComponent(textDefeito, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE)
        							.addComponent(txtEletronico, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE)
        							.addComponent(textAvarias, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 230, GroupLayout.PREFERRED_SIZE))
        						.addGap(45)))
        				.addComponent(lblNewLabel_3)
        				.addComponent(lblNewLabel_4))
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(45)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        							.addGroup(jPanel1Layout.createSequentialGroup()
        								.addComponent(Servico)
        								.addGap(240))
        							.addGroup(jPanel1Layout.createSequentialGroup()
        								.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        									.addComponent(comboBoxServicos, Alignment.LEADING, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(comboBoxTecnico, Alignment.LEADING, 0, 230, Short.MAX_VALUE))
        								.addGap(45)))
        						.addComponent(lblNewLabel_2)
        						.addComponent(lblNewLabel_5)))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(44)
        					.addComponent(textValorTotal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(225))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 577, Short.MAX_VALUE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        						.addComponent(txtIdSO, Alignment.LEADING)
        						.addComponent(jLabel2, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel5)
        						.addComponent(txtDtConclusao, GroupLayout.PREFERRED_SIZE, 142, GroupLayout.PREFERRED_SIZE))
        					.addGap(133)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lblNewLabel)
        						.addComponent(textCpfCliente, GroupLayout.PREFERRED_SIZE, 228, GroupLayout.PREFERRED_SIZE))))
        			.addGap(214))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(jLabel5)
        				.addComponent(lblNewLabel))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtIdSO, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(txtDtConclusao, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(textCpfCliente, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabel_1)
        				.addComponent(Servico))
        			.addGap(5)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(txtEletronico, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(comboBoxServicos, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(8)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabel_3)
        				.addComponent(lblNewLabel_2))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE, false)
        				.addComponent(comboBoxTecnico, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(1)
        					.addComponent(textDefeito, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabel_4)
        				.addComponent(lblNewLabel_5))
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(textAvarias, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(4)
        					.addComponent(textValorTotal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(44))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //executa quando clica no botão
    	String nome, cpf, endereco, telefone, email;
    	
    	nome = txtIdSO.getText();
    	cpf = txtCpf.getText();
    	endereco = txtEletronico.getText();
    	telefone = txtDtConclusao.getText();
    	email = txtServico.getText();
    	
    	
    	long eventMask = 0;
		Tecnico tec = new Tecnico(eventMask, nome, cpf, endereco, telefone, email);
		TecnicoDAO tecDAO = new TecnicoDAO();
    	
    	 if(tecDAO.inserirTecnico(tec)){	
    		 
             JOptionPane.showMessageDialog(null, "Cadastro Realizado com Sucesso!","Resultado",JOptionPane.INFORMATION_MESSAGE);
             
             txtIdSO.setText(null);
         	 txtCpf.setText(null);
         	 txtEletronico.setText(null);
         	 txtDtConclusao.setText(null);
         	 txtServico.setText(null);
         	 
         	 preencherTbl();
         	
         }else{
             JOptionPane.showMessageDialog(null, "NAO FOI POSSÍVEL CADASTRAR!","Resultado",JOptionPane.ERROR_MESSAGE);
         }
    	 
    	 jButtonCadastrar.setEnabled(true);
    	
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */     
    public void preencherTbl() {
    	TecnicoDAO tecDAO = new TecnicoDAO();
    	List<Tecnico> lista = tecDAO.listarTecnicos();
    	
    	DefaultTableModel modelo = (DefaultTableModel) tableTecnicos.getModel();
    	modelo.setRowCount(0);
    	
    	for (Tecnico tecnico : lista) {
    		modelo.addRow(new Object[]{tecnico.getId(),tecnico.getNome(), tecnico.getCpf(), tecnico.getEndereco(), 
    				tecnico.getTelefone(), tecnico.getEmail()});
    	}
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroOrdemServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroOrdemServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtIdSO;
    private javax.swing.JTextField txtEletronico;
    private javax.swing.JTextField txtDtConclusao;
    private javax.swing.JTextField txtBuscarIdSo;
    private JLabel lblNewLabel_1;
    private JLabel Servico;
    private JTextField textValorTotal;
    private JLabel lblNewLabel_2;
    private JComboBox comboBoxServicos;
    private JLabel lblNewLabel;
    private JTextField textCpfCliente;
    private JButton btnNewButton;
    // End of variables declaration//GEN-END:variables
	public void exibeMensagem(String mensagem) {
		JOptionPane.showMessageDialog(null, mensagem);
	}

	public javax.swing.JTextField getjTextFieldNome() {
		return txtIdSO;
	}

	public void setjTextFieldNome(javax.swing.JTextField jTextFieldNome) {
		this.txtIdSO = jTextFieldNome;
	}

	public javax.swing.JTextField getjTextEndereco() {
		return txtEletronico;
	}

	public void setjTextEndereco(javax.swing.JTextField jTextEndereco) {
		this.txtEletronico = jTextEndereco;
	}

	public javax.swing.JTextField getjTextFieldCpf() {
		return txtCpf;
	}

	public void setjTextFieldCpf(javax.swing.JTextField jTextFieldCpf) {
		this.txtCpf = jTextFieldCpf;
	}

	public javax.swing.JTextField getjTextFieldEmail() {
		return txtServico;
	}

	public void setjTextFieldEmail(javax.swing.JTextField jTextFieldEmail) {
		this.txtServico = jTextFieldEmail;
	}

	public javax.swing.JTextField getjTextFieldTelefone() {
		return txtDtConclusao;
	}

	public void setjTextFieldTelefone(javax.swing.JTextField jTextFieldTelefone) {
		this.txtDtConclusao = jTextFieldTelefone;
	}
}
